import Footer from "@/components/Footer/Footer";
import { nunito_sans } from "../../font";
import "./globals.css";
import Header from "@/components/Header/Header";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={` max-w-[1920px] mx-auto ${nunito_sans.className}`}>
        <TooltipProvider>
          <Header />
          {children}
          <Footer />
        </TooltipProvider>
      </body>
    </html>
  );
}
